export const booksData = [
  {
    id: 1,
    title: 'Atomic Habits',
    author: 'James Clear',
    year: '2018',
    description: 'Perubahan kecil yang memberikan hasil luar biasa dalam membangun kebiasaan baik.',
    price: 'Rp 85.000',
    cover: 'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg',
    category: 'Self Improvement',
  },
  {
    id: 2,
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    year: '2020',
    description: 'Pelajaran abadi mengenai kekayaan, ketamakan, dan kebahagiaan keuangan.',
    price: 'Rp 95.000',
    cover: 'https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg',
    category: 'Finance',
  },
  {
    id: 3,
    title: 'Deep Work',
    author: 'Cal Newport',
    year: '2016',
    description: 'Aturan untuk meraih sukses fokus di dunia yang penuh dengan gangguan.',
    price: 'Rp 78.000',
    cover: 'https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg',
    category: 'Productivity',
  },
  {
    id: 4,
    title: 'Rich Dad Poor Dad',
    author: 'Robert Kiyosaki',
    year: '1997',
    description: 'Apa yang diajarkan orang kaya pada anak-anak mereka tentang pengelolaan uang.',
    price: 'Rp 72.000',
    cover: 'https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg',
    category: 'Finance',
  },
  {
    id: 5,
    title: 'Clean Code',
    author: 'Robert C. Martin',
    year: '2008',
    description: 'Panduan pengembangan dan penulisan kode perangkat lunak yang bersih dan efisien.',
    price: 'Rp 120.000',
    cover: 'https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg',
    category: 'Programming',
  },
  {
    id: 6,
    title: 'The Lean Startup',
    author: 'Eric Ries',
    year: '2011',
    description: 'Cara pengusaha saat ini menggunakan inovasi berkelanjutan untuk menciptakan bisnis.',
    price: 'Rp 88.000',
    cover: 'https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg',
    category: 'Business',
  },
  {
    id: 7,
    title: 'Sebuah Seni untuk Bersikap Bodo Amat',
    author: 'Mark Manson',
    year: '2016',
    description: 'Pendekatan yang tidak biasa untuk hidup dengan lebih tenang dan bahagia.',
    price: 'Rp 75.000',
    cover: 'https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg',
    category: 'Self Improvement',
  },
  {
    id: 8,
    title: 'Zero to One',
    author: 'Peter Thiel',
    year: '2014',
    description: 'Catatan tentang startup dan bagaimana membangun masa depan inovasi.',
    price: 'Rp 90.000',
    cover: 'https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg',
    category: 'Business',
  },
  {
    id: 9,
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    year: '2014',
    description: 'Riwayat singkat perjalanan dan evolusi spesies manusia di bumi.',
    price: 'Rp 115.000',
    cover: 'https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg',
    category: 'History',
  },
];

export const books = booksData;
